version: '2'
services:
  Cservice:
    container_name: composerContainer
    image: composer
    volumes:
     - .:/app
    command: ["install"]
  phpservice:
    container_name: ${NAME_APP_CONTAINER}
    depends_on:
     - dbservice
    image: webdevops/php-apache
    volumes:
     - .:/app/
    ports:
     - ${HTTP_PORT}:80
     - ${HTTPS_PORT}:443

  dbservice:
    container_name: ${NAME_DB_CONTAINER}
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_DATABASE=${MYSQL_DATABASE}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
     - ./data:/var/lib/mysql
    ports:
     - ${MYSQL_PORT}:3306
